name: CI CD Master

on:
  push:
    branches:
      - master

env:
  flutter_version: "2.10.2"
  java_version: "11.x"

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      
      - name: Read pubspec.yaml Version
        uses: KJ002/read-yaml@1.5
        id: pubspec-data
        with:
          file: 'pubspec.yaml'
          key-path: '["version"]'

      - name: Setup java_version
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.java_version}}

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{runner.OS}}-flutter-install-cache-${{env.flutter_version}}
      - name: Setup Flutter 
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{env.flutter_version}}
          channel: 'stable'
      
      - name: Pubg Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Save APK to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/flutter-apk/app-release.apk